### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by thiagodelgado111** [orbitdb/orbit-db-store#31]
## TODO

- [ ] Move Cache to the store
- [ ] Throw errors if a required argument isn't passed to the store
- [ ] Remove `.id` property since it's the same as the address
- [ ] Make the Store extend EventEmitter
- [ ] Clean up replication event handling
- [ ] Move snapshot related code to its own space
- [ ] Remove Index from Store
- [ ] Should we rename Index to IndexingStrategy?
- [ ] Should Cache be named like that since it feels it does more than just caching data?
- [ ] Add "store builder"

**Comment by thiagodelgado111** [comment]
Thanks for checking it out! About the store builder, that must have sneaked into my notes somehow, removed it!

**Comment by aphelionz** [comment]
Hi @thiagodelgado111! With regards to the last two unchecked items - how are those going/ Might I be able to assist in any way?

- [ ] Remove Index from Store
- [ ] Should we rename Index to IndexingStrategy?
